---
- name: Pre-reqs for ansible to run
  hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || ( yum -y update && yum install -y python-minimal )

- name: Build Data Ingest Linux Server.
  hosts: all
  become: true
  tasks:
  - name: Set machine hostname
    hostname:
      name: LINUX-BASTION1

  - name: Set timezone to Europe/London
    timezone:
      name: Europe/London

  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Create site-enabled directory
    file:
      path: /etc/nginx/html/site-enabled
      state: directory

  - name: Create moved file directory
    file:
      path: /movedfiles
      state: directory

  - name: Create files to be moved
    file:
      path: "/file1.txt file2.txt file3.txt"
      state: touch

  - name: Insert app.conf file into direcoty
    template:
      src: app.conf
      dest: /etc/nginx/html/site-enabled/app.conf

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: Move file to movefiles dir
    copy: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'file1.txt', dest: '/movedfiles' }
      - { src: 'file2.txt', dest: '/movedfiles' }
      - { src: 'file3.txt', dest: '/movedfiles' }

  # - debug: var=output.stdout_lines      regexp="^PasswordAuthentication"
  #             line="PasswordAuthentication no"
  #             state=present
