---
- name: Pre-reqs for ansible to run
  hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || ( yum -y update && yum install -y python-minimal )

- name: Build Data Ingest Linux Server.
  hosts: all
  become: true
  tasks:
  - name: Set machine hostname
    hostname:
      name: LINUX-BASTION1

  - name: Set timezone to Europe/London
    timezone:
      name: Europe/London

  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: app.conf
      dest: /etc/nginx/html/site-enabled/app.conf

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  # - debug: var=output.stdout_lines      regexp="^PasswordAuthentication"
  #             line="PasswordAuthentication no"
  #             state=present
