---
- name: Pre-reqs for ansible to run
  hosts: all
  gather_facts: false
  become: yes
  pre_tasks:
    - raw: test -e /usr/bin/python || ( dnf clean packages && dnf install -y python39 && ln -s -f /usr/bin/python3.9 /usr/bin/python)

- name: Build Data Ingest Linux Server.
  hosts: all
  become: true
  tasks:
  - name: Set machine hostname
    shell: |
      hostname LINUX-BASTION1
      echo "LINUX-BASTION1" > /etc/hostname

  - name: Set timezone to Europe/London
    timezone:
      name: Europe/London

  - name: Add hostname to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1[ \t]+localhost'
      line: '127.0.0.1 localhost LINUX-BASTION1'
      state: present
    vars:
      ansible_python_interpreter: "/usr/libexec/platform-python" 

  - name: DNF Update
    shell: |
       sed -i 's/REGION/eu-west-2/' /etc/yum.repos.d/redhat-rhui*.repo
       dnf update -y
       dnf install -y libselinux-python3
       dnf install -y postgresql
    become: true
    vars:
      ansible_python_interpreter: "/usr/libexec/platform-python" 

  - name: Download cloudwatch logs agent
    get_url:
      url: https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
      dest: /tmp/awslogs-agent-setup.py
      mode: "+x"
    vars:
      ansible_python_interpreter: "/usr/libexec/platform-python" 

  - name: Cloudwatch logs config
    copy:
      dest: /tmp/cwlogs.conf
      content: |
        [general]
        state_file = /var/awslogs/state/agent-state
        [/var/log/syslog]
        file = /var/log/syslog
        log_group_name = /Centos_Server/system
        log_stream_name = {instance_id}
        datetime_format = %b %d %H:%M:%S
        [/Centos_Server/cloud-init]
        file = /var/log/cloud-init.log
        log_group_name = /Centos_Server/cloud-init
        log_stream_name = {instance_id}
        datetime_format = %Y-%m-%d %H:%M:%S,%f
        [/Centos_Server/cloud-init/output]
        file = /var/log/cloud-init-output.log
        log_group_name = /Centos_Server/cloud-init/output
        log_stream_name = {instance_id}
        datetime_format = %Y-%m-%d %H:%M:%S,%f
    vars:
      ansible_python_interpreter: "/usr/libexec/platform-python" 

  - name: Install cloudwatch log agent
    environment:
      LC_ALL: C
    shell: /tmp/awslogs-agent-setup.py --region eu-west-2 --non-interactive -c /tmp/cwlogs.conf
    args:
      creates: /var/awslogs/etc/aws.conf
    vars:
      ansible_python_interpreter: "/usr/libexec/platform-python" 

  - name: Copy cloudwatch logs starter
    copy:
      src: startcloudwatchlogs.sh
      dest: /usr/bin/startcloudwatchlogs.sh
      owner: root
      group: root
      mode: 0755
    vars:
      ansible_python_interpreter: "/usr/libexec/platform-python" 

  - name: Make Cron Job to start awslogs with right region
    cron:
      name: Start awslogs
      special_time: reboot
      job: /usr/bin/startcloudwatchlogs.sh
    vars:
      ansible_python_interpreter: "/usr/libexec/platform-python" 

  - name: Secure sshd_config
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin no"
                state=present
  - lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
  - lineinfile: dest=/etc/ssh/sshd_config
                regexp="^X11Forwarding"
                line="X11Forwarding no"
                state=present
    vars:
      ansible_python_interpreter: "/usr/libexec/platform-python" 
